#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 19 09:08:00 2020

@author: larsno
"""

def area(vertices):
    "Compute area of a polygon given a list of vertices"
    
    # Add v0 to end of list
    vertices.append(vertices[0])
    
    A = 0.0
    for i in range(len(vertices) - 1):
        A += vertices[i][0]*vertices[i+1][1] - vertices[i+1][0]*vertices[i][1] 
    
    return abs(A)/2

# Create tuples of vertex coordinates for a triangle and compute area
vertices = [(0.0, 0.0), (0.0, 2.0), (3.0, 0.0)]
A = area(vertices)
print(A)

